/**
 * Conversational AI using RLHF - Multi-Model Backend
 * Supports: Claude (Anthropic) - Gemini (Google) - Groq (Llama3 / Mixtral)
 * Zero npm dependencies - Node.js built-ins only
 * Run: node server.js
 */

const http  = require('http');
const https = require('https');
const fs    = require('fs');
const path  = require('path');
const url   = require('url');

const PORT = process.env.PORT || 3000;

// -- Load .env (Zero dependencies) -------------------
try {
    const envPath = path.join(__dirname, '.env');
    if (fs.existsSync(envPath)) {
          fs.readFileSync(envPath, 'utf8').split('\n').forEach(line => {
                  const parts = line.split('=');
                  if (parts.length >= 2) {
                            const key = parts[0].trim();
                            const val = parts.slice(1).join('=').trim().replace(/^["']|["']$/g, '');
                            if (key && !process.env[key]) process.env[key] = val;
                  }
          });
    }
} catch (err) { /* ignore */ }

// -- API Keys ------------------------------------------
const KEYS = {
    claude: process.env.ANTHROPIC_API_KEY || '',
    gemini: process.env.GEMINI_API_KEY    || 'AIzaSyBALPPe4X3nrvgGPS5vgKymAiYX_uamRf4',
    groq:   process.env.GROQ_API_KEY      || '',
};

const MIME = {
    '.html': 'text/html', '.css': 'text/css',
    '.js': 'application/javascript', '.json': 'application/json',
    '.png': 'image/png', '.ico': 'image/x-icon', '.svg': 'image/svg+xml',
};

// -- Shared NLP system prompt --------------------------
const SYSTEM_PROMPT = `You are an expert NLP analysis engine for a "Conversational AI using RLHF" project.
Analyze the user message and return ONLY valid JSON - no markdown fences, no explanation, no preamble.

Return this exact JSON structure:
{
  "tokens": [{"word":"string","tag":"intent|entity|utterance|filler|ambiguous","score":0-100}],
    "overall_scores": {"clarity":0-100,"specificity":0-100,"context":0-100,"total":0-100},
      "intent_type": "Question|Command|Clarification|Creative|Technical|Emotional",
        "content_domain": "Coding|Writing|Research|Design|Business|General",
          "improved_prompts": [
              {"label":"Structured","text":"rewritten in clear structured format","improvement_score":0-100},
                  {"label":"Role-Framed","text":"version with expert role + context","improvement_score":0-100},
                      {"label":"Chain-of-Thought","text":"step-by-step reasoning version","improvement_score":0-100}
                        ]
                        }

                        Rules:
                        - tokens: tag EVERY word; score = contribution to NLP clarity (0-100)
                        - overall_scores.total = clarity*0.35 + specificity*0.35 + context*0.30
                        - improvement_score = relative gain vs original (0-100)
                        - Return ONLY the raw JSON object, nothing else.`;

// -- Generic HTTPS request helper ----------------------
function httpsPost(options, body) {
    return new Promise((resolve, reject) => {
          const req = https.request(options, (res) => {
                  let data = '';
                  res.on('data', c => data += c);
                  res.on('end', () => {
                            try {
                                        const json = JSON.parse(data);
                                        if (res.statusCode < 200 || res.statusCode >= 300) {
                                                      const msg = json.error?.message || json.error?.msg || \`HTTP \${res.statusCode}\`;
                                                                  reject({ status: res.statusCode, message: msg });
                                                                            } else {
                                                                                        resolve(json);
                                                                                                  }
                                                                                                          } catch {
                                                                                                                    reject({ status: 500, message: 'Could not parse API response' });
                                                                                                                            }
                                                                                                                                  });
                                                                                                                                      });
                                                                                                                                          req.on('error', e => reject({ status: 503, message: e.message }));
                                                                                                                                              req.write(body);
                                                                                                                                                  req.end();
                                                                                                                                                    });
                                                                                                                                                    }
                                                                                                                                                    
                                                                                                                                                    // -- Extract text from raw API response ----------------
                                                                                                                                                    function extractText(raw) {
                                                                                                                                                      if (!raw || typeof raw !== 'string') return null;
                                                                                                                                                        let parsed;
                                                                                                                                                          try { parsed = JSON.parse(raw.replace(/\\\`\\\`\\\`json|\\\`\\\`\\\`/g, '').trim()); return parsed; } catch {}
                                                                                                                                                            const m = raw.match(/\\{[\\s\\S]*\\}/);
                                                                                                                                                              if (m) { try { return JSON.parse(m[0]); } catch {} }
                                                                                                                                                                return null;
                                                                                                                                                                }
                                                                                                                                                                
                                                                                                                                                                // -- Model callers -------------------------------------
                                                                                                                                                                
                                                                                                                                                                // Claude (Anthropic)
                                                                                                                                                                function callClaude(message, model) {
                                                                                                                                                                  const body = JSON.stringify({
                                                                                                                                                                      model: model || 'claude-haiku-4-5-20251001',
                                                                                                                                                                          max_tokens: 1024,
                                                                                                                                                                              system: SYSTEM_PROMPT,
                                                                                                                                                                                  messages: [{ role: 'user', content: message }]
                                                                                                                                                                                    });
                                                                                                                                                                                      return httpsPost({
                                                                                                                                                                                          hostname: 'api.anthropic.com', port: 443, path: '/v1/messages', method: 'POST',
                                                                                                                                                                                              headers: {
                                                                                                                                                                                                    'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body),
                                                                                                                                                                                                          'x-api-key': KEYS.claude, 'anthropic-version': '2023-06-01'
                                                                                                                                                                                                              }
                                                                                                                                                                                                                }, body).then(r => r.content?.[0]?.text || '{}');
                                                                                                                                                                                                                }
                                                                                                                                                                                                                
                                                                                                                                                                                                                // Gemini (Google) - free tier available
                                                                                                                                                                                                                function callGemini(message, model) {
                                                                                                                                                                                                                  const m = model || 'gemini-2.5-flash';
                                                                                                                                                                                                                    const body = JSON.stringify({
                                                                                                                                                                                                                        contents: [{ parts: [{ text: SYSTEM_PROMPT + '\\n\\nUser message: ' + message }] }],
                                                                                                                                                                                                                            generationConfig: { maxOutputTokens: 4096, temperature: 0.3, responseMimeType: 'application/json' }
                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                return httpsPost({
                                                                                                                                                                                                                                    hostname: 'generativelanguage.googleapis.com', port: 443,
                                                                                                                                                                                                                                        path: \`/v1beta/models/\${m}:generateContent?key=\${KEYS.gemini}\`,
                                                                                                                                                                                                                                            method: 'POST',
                                                                                                                                                                                                                                                headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) }
                                                                                                                                                                                                                                                  }, body).then(r => r.candidates?.[0]?.content?.parts?.[0]?.text || '{}');
                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                  // Groq - free tier: llama3, mixtral, gemma
                                                                                                                                                                                                                                                  function callGroq(message, model) {
                                                                                                                                                                                                                                                    const body = JSON.stringify({
                                                                                                                                                                                                                                                        model: model || 'llama3-8b-8192',
                                                                                                                                                                                                                                                            max_tokens: 1024,
                                                                                                                                                                                                                                                                temperature: 0.3,
                                                                                                                                                                                                                                                                    messages: [
                                                                                                                                                                                                                                                                          { role: 'system', content: SYSTEM_PROMPT },
                                                                                                                                                                                                                                                                                { role: 'user', content: message }
                                                                                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                        return httpsPost({
                                                                                                                                                                                                                                                                                            hostname: 'api.groq.com', port: 443, path: '/openai/v1/chat/completions', method: 'POST',
                                                                                                                                                                                                                                                                                                headers: {
                                                                                                                                                                                                                                                                                                      'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body),
                                                                                                                                                                                                                                                                                                            'Authorization': \`Bearer \${KEYS.groq}\`
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                  }, body).then(r => r.choices?.[0]?.message?.content || '{}');
                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                  // -- Route to correct provider -------------------------
                                                                                                                                                                                                                                                                                                                  async function callModel(provider, model, message) {
                                                                                                                                                                                                                                                                                                                    switch (provider) {
                                                                                                                                                                                                                                                                                                                        case 'claude':  return callClaude(message, model);
                                                                                                                                                                                                                                                                                                                            case 'gemini':  return callGemini(message, model);
                                                                                                                                                                                                                                                                                                                                case 'groq':    return callGroq(message, model);
                                                                                                                                                                                                                                                                                                                                    default: throw { status: 400, message: \`Unknown provider: \${provider}\` };
                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                      // -- Helpers -------------------------------------------
                                                                                                                                                                                                                                                                                                                                      function readBody(req) {
                                                                                                                                                                                                                                                                                                                                        return new Promise((resolve, reject) => {
                                                                                                                                                                                                                                                                                                                                            let body = '';
                                                                                                                                                                                                                                                                                                                                                req.on('data', c => { body += c; if (body.length > 20000) reject(new Error('Too large')); });
                                                                                                                                                                                                                                                                                                                                                    req.on('end', () => { try { resolve(JSON.parse(body)); } catch { resolve({}); } });
                                                                                                                                                                                                                                                                                                                                                        req.on('error', reject);
                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                          function sendJSON(res, status, obj) {
                                                                                                                                                                                                                                                                                                                                                            res.writeHead(status, {
                                                                                                                                                                                                                                                                                                                                                                'Content-Type': 'application/json',
                                                                                                                                                                                                                                                                                                                                                                    'Access-Control-Allow-Origin': '*',
                                                                                                                                                                                                                                                                                                                                                                        'Access-Control-Allow-Headers': 'Content-Type',
                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                            res.end(JSON.stringify(obj));
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                            function serveFile(res, filePath) {
                                                                                                                                                                                                                                                                                                                                                                              fs.readFile(filePath, (err, data) => {
                                                                                                                                                                                                                                                                                                                                                                                  if (err) { res.writeHead(404); return res.end('Not found'); }
                                                                                                                                                                                                                                                                                                                                                                                      res.writeHead(200, { 'Content-Type': MIME[path.extname(filePath)] || 'text/plain' });
                                                                                                                                                                                                                                                                                                                                                                                          res.end(data);
                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            // -- HTTP Server ---------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                            http.createServer(async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                              const { pathname } = url.parse(req.url);
                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                if (req.method === 'OPTIONS') {
                                                                                                                                                                                                                                                                                                                                                                                                    res.writeHead(204, {
                                                                                                                                                                                                                                                                                                                                                                                                          'Access-Control-Allow-Origin': '*',
                                                                                                                                                                                                                                                                                                                                                                                                                'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
                                                                                                                                                                                                                                                                                                                                                                                                                      'Access-Control-Allow-Headers': 'Content-Type'
                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                              return res.end();
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                  // POST /api/analyze
                                                                                                                                                                                                                                                                                                                                                                                                                                    if (req.method === 'POST' && pathname === '/api/analyze') {
                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                              const { message = '', provider = 'claude', model = '' } = await readBody(req);
                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!message.trim()) return sendJSON(res, 400, { error: 'Message is required' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const key = KEYS[provider];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!key) return sendJSON(res, 500, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        error: \`API key for "\${provider}" not set. See README for setup instructions.\`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                keyVar: { claude: 'ANTHROPIC_API_KEY', gemini: 'GEMINI_API_KEY', groq: 'GROQ_API_KEY' }[provider]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const rawText = await callModel(provider, model, message.trim());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const parsed  = extractText(rawText);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!parsed) return sendJSON(res, 500, { error: 'AI returned invalid JSON. Try again.' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return sendJSON(res, 200, { success: true, data: parsed, provider, model });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.error(\`[\${new Date().toISOString()}] API error:\`, err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (err.status === 401) return sendJSON(res, 401, { error: 'Invalid API key - double-check your key' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (err.status === 429) return sendJSON(res, 429, { error: 'Rate limit hit - wait a moment and retry' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (err.status === 403) return sendJSON(res, 403, { error: 'Access denied - check your API key permissions' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return sendJSON(res, 500, { error: err.message || 'Request failed' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // GET /api/health
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (req.method === 'GET' && pathname === '/api/health') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return sendJSON(res, 200, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status: 'ok',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          keys: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  claude: KEYS.claude ? 'set' : 'missing',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          gemini: KEYS.gemini ? 'set' : 'missing',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  groq:   KEYS.groq   ? 'set' : 'missing',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Static files
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (req.method === 'GET') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const publicDir = path.join(__dirname, 'public');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const filePath  = pathname === '/' ? path.join(publicDir, 'index.html') : path.join(publicDir, pathname);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!filePath.startsWith(publicDir)) { res.writeHead(403); return res.end('Forbidden'); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return serveFile(res, filePath);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      res.writeHead(404); res.end('Not found');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }).listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const k = KEYS;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log('\\n----------------------------------------------------');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log('|    Conversational AI using RLHF  (Multi-Model)  |');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log('----------------------------------------------------');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(\`\\n  URL  ->  http://localhost:\${PORT}\\n\`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.log(\`  Claude   (Anthropic) ->  \${k.claude ? 'READY' : 'Set ANTHROPIC_API_KEY'}\`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(\`  Gemini  (Google)    ->  \${k.gemini ? 'READY' : 'Set GEMINI_API_KEY'}\`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(\`  Groq    (Llama3)    ->  \${k.groq   ? 'READY' : 'Set GROQ_API_KEY'}\`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log('\\n  You only need ONE key to get started.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log('  Press Ctrl+C to stop\\n');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
